version: '3.8'

services:
  visionVFX_postgres:
    image: postgres:alpine
    container_name: visionVFX_postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - '5432:5432'
    volumes:
      - visionVFX_postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: visionVFX_network #

volumes:
  visionVFX_postgres_data:
